name: easyhome
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^8.1.3
  build_runner: ^2.4.8
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  direct_caller_sim_choice: ^1.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_phone_direct_caller: ^2.1.1
  flutter_screenutil: ^5.9.0
  font_awesome_flutter: ^10.7.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.7  
  multiple_images_picker: ^1.0.1
  flutter_rating_bar: ^4.0.1
  email_validator: '^2.1.16'
  provider: ^6.1.2
  readmore: ^3.0.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/utils/images/

    
    

